# Generated by Django 5.1.12 on 2025-10-06 13:16

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [UnaccentExtension(),]
