language: python
python:
  - "3.7"
services:
  - elasticsearch
before_install:
  - curl https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.6/elasticsearch-2.4.6.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
before_script:
  - sleep 10
install:
  - pip install tox==3.14.0 tox-travis==0.12
script:
  - cp kart/site_settings.py.dev kart/site_settings.py
  - tox
