language: python
python:
  - "3.8"
services:
  - elasticsearch
before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.1-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
before_script:
  - sleep 10
install:
  - pip install tox==3.14.0 tox-travis==0.12
script:
  - cp kart/site_settings.py.dev kart/site_settings.py  
  - for file in school/templates/emails/*.dev; do cp $file ${file%.dev}; done
  - tox
