language: python
python:
  - "3.7"
install:
  - pip install tox==3.14.0 tox-travis==0.12
script:
  - cp kart/site_settings.py.dev kart/site_settings.py  
  - for file in school/templates/emails/*.dev; do cp $file ${file%.dev}; done
  - tox
