language: python
python:
  - "3.8"
services:
  - elasticsearch
before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.1-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo echo 'xpack.security.enabled:false' >> /etc/elasticsearch/elasticsearch.yml
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
before_script:
  - sleep 10
install:
  - pip install tox==3.14.0 tox-travis==0.12
script:
  - cp kart/site_settings.py.dev kart/site_settings.py  
  - for file in school/templates/emails/*.dev; do cp $file ${file%.dev}; done
  - tox
