# Generated by Django 4.2.16 on 2024-11-28 15:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0005_migration_to_django2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2, null=True
            ),
        ),
    ]
