# Generated by Django 2.1.7 on 2019-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'English')], max_length=2)),
                ('url', models.URLField()),
            ],
        ),
    ]
