# Generated by Django 2.2.6 on 2019-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTBeacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(unique=True)),
                ('rssi_in', models.IntegerField()),
                ('rssi_out', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'English')], max_length=2)),
                ('url', models.URLField()),
            ],
        ),
    ]
