# Generated by Django 2.2.6 on 2019-12-20 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='people.Artist'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Promotion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_application', to='people.Artist'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='school.StudentApplicationSetup'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='cursus_justifications',
            field=models.ForeignKey(blank=True, help_text='Gallery of justificaitons', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_application_cursus_justification', to='assets.Gallery'),
        ),
        migrations.AlterField(
            model_name='studentapplicationsetup',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Promotion'),
        ),
    ]
