# Generated by Django 3.2.15 on 2023-06-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_languagesfield_newversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0011_add_school_prof_student_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='visiting_student', to='people.artist')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
