# Generated by Django 4.1 on 2023-10-12 12:36

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    """
    Transfert data from StudentApplication to AdminStudentApplication
    """
    admin_app = apps.get_model("school", "AdminStudentApplication")
    student_application = apps.get_model("school", "StudentApplication")
    list_transfert = ["observation", "selected_for_interview", "interview_date", "wait_listed_for_interview", 
                      "position_in_interview_waitlist", "selected", "unselected", "wait_listed", 
                      "position_in_waitlist", "application_complete"]


    for sa in student_application.objects.all():
        admin = admin_app.objects.create(application=sa)
        for field in list_transfert:
            val = getattr(sa, field)
            setattr(admin, field, val)
        admin.save()


def backwards_func(apps, schema_editor):
    """
    Transfert AdminStudentApplication data to StudentApplication
    """
    admin_app = apps.get_model("school", "AdminStudentApplication")
    list_transfert = ["observation", "selected_for_interview", "interview_date", "wait_listed_for_interview", 
                      "position_in_interview_waitlist", "selected","unselected","wait_listed", 
                      "position_in_waitlist", "application_complete"]


    for admin in admin_app.objects.all():
        app = admin.application
        for field in list_transfert:
            val = getattr(admin, field)
            setattr(app, field, val)
        app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_add_visitingstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, help_text='Comments on the application', null=True)),
                ('selected_for_interview', models.BooleanField(default=False, help_text='Is the candidat selected for the Interview')),
                ('interview_date', models.DateTimeField(blank=True, help_text='Date for interview', null=True)),
                ('wait_listed_for_interview', models.BooleanField(default=False, help_text='Is the candidat wait listed for the Interview')),
                ('position_in_interview_waitlist', models.PositiveSmallIntegerField(blank=True, help_text='Set the position in interview waitlist', null=True)),
                ('selected', models.BooleanField(default=False, help_text='Is the candidat selected')),
                ('unselected', models.BooleanField(default=False, help_text='Is the candidat not choosen by the Jury')),
                ('wait_listed', models.BooleanField(default=False, help_text='Is the candidat wait listed')),
                ('position_in_waitlist', models.PositiveSmallIntegerField(blank=True, help_text='Set the position in waitlist', null=True)),
                ('application_complete', models.BooleanField(default=False, help_text='Candidature is complete')),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration', to='school.studentapplication')),
            ],
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name='studentapplication',
            name='application_complete',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='position_in_interview_waitlist',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='position_in_waitlist',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='selected_for_interview',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='unselected',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='wait_listed',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='wait_listed_for_interview',
        ),
    ]
