# Generated by Django 4.1 on 2023-10-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_adminschoolapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phdstudent',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='sciencestudent',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['artist__user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='teachingartist',
            options={'ordering': ['artist']},
        ),
        migrations.AlterModelOptions(
            name='visitingstudent',
            options={'ordering': ['artist']},
        ),
    ]
