# Generated by Django 5.1.12 on 2025-09-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0018_alter_student_with_optional_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplicationsetup",
            name="application_reminder_email_date_2",
            field=models.DateField(
                blank=True, help_text="Another date for reminder", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visitingstudent",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
