# Generated by Django 5.1.7 on 2025-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_gallery_deletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="copyright",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medium",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medium",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
