# Generated by Django 2.2.6 on 2019-11-08 13:36

from django.db import migrations, models
import django.db.models.deletion
import production.models
import sortedm2m.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('diffusion', '0002_initial_resume'),
        ('production', '0001_initial'),
        ('people', '0001_initial'),
        ('assets', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diffusion.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='subevents',
            field=models.ManyToManyField(blank=True, limit_choices_to=production.models.main_event_false_limit, related_name='parent_event', to='production.Event'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='authors',
            field=models.ManyToManyField(related_name='artworks', to='people.Artist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='beacons',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='common.BTBeacon'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='in_situ_galleries',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='artworks_insitu', to='assets.Gallery'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='mediation_galleries',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='artworks_mediation', to='assets.Gallery'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='press_galleries',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='artworks_press', to='assets.Gallery'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='process_galleries',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='artworks_process', to='assets.Gallery'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='teaser_galleries',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='artworks_teaser', to='assets.Gallery'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryartwork',
            unique_together={('itinerary', 'order'), ('itinerary', 'artwork')},
        ),
        migrations.AddField(
            model_name='installation',
            name='genres',
            field=models.ManyToManyField(to='production.InstallationGenre'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='production.FilmGenre'),
        ),
        migrations.AddField(
            model_name='film',
            name='shooting_place',
            field=models.ManyToManyField(blank=True, to='diffusion.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='events', to='production.Film'),
        ),
        migrations.AddField(
            model_name='event',
            name='installations',
            field=models.ManyToManyField(blank=True, related_name='events', to='production.Installation'),
        ),
        migrations.AddField(
            model_name='event',
            name='performances',
            field=models.ManyToManyField(blank=True, related_name='events', to='production.Performance'),
        ),
    ]
