# Generated by Django 2.2.6 on 2019-12-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diffusion.Place'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='event',
            field=models.ForeignKey(limit_choices_to={'type': 'EXHIB'}, on_delete=django.db.models.deletion.PROTECT, related_name='itineraries', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Organization'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_tasks', to='production.Production'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.OrganizationTask'),
        ),
        migrations.AlterField(
            model_name='productionstafftask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.StaffTask'),
        ),
    ]
