# Generated by Django 2.2.6 on 2019-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coucou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
