# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 13:41
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('diffusion', '0002_production_award'),
        ('production', '0007_task_and_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(default=False, help_text=b'Meta Event'),
        ),
        migrations.AddField(
            model_name='film',
            name='shooting_place',
            field=models.ManyToManyField(blank=True, to='diffusion.Place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subevents',
            field=models.ManyToManyField(blank=True, related_name='parent_event', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(b'FEST', b'Festival'), (b'COMP', b'Competition'), (b'PROJ', b'Projection'), (b'EXHIB', b'Exhibition'), (b'VARN', b'Varnishing'), (b'PARTY', b'Party'), (b'WORKSHOP', b'Workshop'), (b'EVENING', b'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='production.FilmGenre'),
        ),
        migrations.AlterField(
            model_name='production',
            name='picture',
            field=models.ImageField(blank=True, upload_to=common.utils.make_filepath),
        ),
    ]
