# Generated by Django 2.2.6 on 2020-01-08 11:01

from django.db import migrations, models
import django.db.models.deletion
import production.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_production_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(default=False, help_text='Meta Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diffusion.Place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subevents',
            field=models.ManyToManyField(blank=True, limit_choices_to=production.models.main_event_false_limit, related_name='parent_event', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FEST', 'Festival'), ('COMP', 'Competition'), ('PROJ', 'Projection'), ('EXHIB', 'Exhibition'), ('VARN', 'Varnishing'), ('PARTY', 'Party'), ('WORKSHOP', 'Workshop'), ('EVENING', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('1.33', '1.33 (4/3)'), ('1.37', '1.37'), ('1.66', '1.66'), ('1.77', '1.77 (16/9)'), ('1.85', '1.85 (Flat)'), ('1.90', '1.90 (Full Container)'), ('2.39', '2.39 (Scope)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(blank=True, help_text='Sous la forme HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='process',
            field=models.CharField(blank=True, choices=[('COLOR', 'Couleur'), ('BW', 'Noir & Blanc'), ('COLORBW', 'NB & Couleur'), ('SEPIA', 'Sépia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='shooting_format',
            field=models.CharField(blank=True, choices=[('SUP8', 'Super 8'), ('SUP16', 'Super 16'), ('SUP35', 'Super 35'), ('35MM', '35 MM'), ('70MM', '70 MM'), ('DV', 'DV'), ('DVCAM', 'DV-CAM'), ('HD', 'HD'), ('HDCAM', 'HD-CAM'), ('HDCINE', 'HD CINEMASCOPE'), ('CREANUM', 'CREATION NUMERIQUE'), ('BETASP', 'BETA SP'), ('BETANUM', 'BETA NUM.'), ('DIGICAM', 'APPAREIL PHOTO'), ('MOBILE', 'MOBILE'), ('HI8', 'HI8'), ('AVCHD', 'AVCHD'), ('XDCAMEX', 'XDcamEX'), ('3DREL', 'RELIEF 3D'), ('2K', '2K'), ('4K', '4K')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='event',
            field=models.ForeignKey(limit_choices_to={'type': 'EXHIB'}, on_delete=django.db.models.deletion.PROTECT, related_name='itineraries', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Organization'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_tasks', to='production.Production'),
        ),
        migrations.AlterField(
            model_name='productionorganizationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.OrganizationTask'),
        ),
        migrations.AlterField(
            model_name='productionstafftask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.StaffTask'),
        ),
    ]
