# Generated by Django 2.2.6 on 2020-11-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_migration_to_django2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstafftask',
            options={'ordering': ['pk']},
        ),
    ]
