# Generated by Django 5.1.7 on 2025-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0013_film_create_languagesVOSUB_update_moviespec"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="picture_copyright",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
