# Generated by Django 5.1.15 on 2026-03-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0014_copyright_main_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="exhibition",
            options={},
        ),
        migrations.AlterModelOptions(
            name="film",
            options={},
        ),
        migrations.AlterModelOptions(
            name="installation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="performance",
            options={},
        ),
    ]
