# Generated by Django 2.2.6 on 2019-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_aequo', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('amount', models.CharField(blank=True, help_text='money, visibility, currency free', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Free note')),
            ],
        ),
        migrations.CreateModel(
            name='Diffusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, choices=[('WORLD', 'Mondial'), ('INTER', 'International'), ('NATIO', 'National')], help_text='Qualifies the first broadcast', max_length=5, null=True)),
                ('on_competition', models.BooleanField(default=False, help_text='IN / OFF : On competion or not')),
            ],
        ),
        migrations.CreateModel(
            name='MetaAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('CAREER', 'Career'), ('OTHER', 'Other')], max_length=10, null=True)),
            ],
        ),
    ]
