# Generated by Django 2.2.6 on 2019-11-08 13:36

import diffusion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('production', '0001_initial'),
        ('people', '0001_initial'),
        ('diffusion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, help_text='Code postal / Zipcode', max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='people.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='MetaEvent',
            fields=[
                ('event', models.OneToOneField(limit_choices_to=diffusion.models.main_event_true, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='meta_event', serialize=False, to='production.Event')),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('FILM', 'Films'), ('PERF', 'Performances'), ('INST', 'Installations')], help_text='Global kind of productions shown', max_length=14)),
                ('important', models.BooleanField(default=True, help_text='Helps hide minor events')),
                ('keywords', taggit.managers.TaggableManager(blank=True, help_text='Qualifies Festival: digital arts, residency, electronic festival', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='metaaward',
            name='event',
            field=models.ForeignKey(help_text='Main Event', limit_choices_to=diffusion.models.main_event_true, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_award', to='production.Event'),
        ),
        migrations.AddField(
            model_name='metaaward',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_award', to='production.StaffTask'),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='diffusion', to='production.Artwork'),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='event',
            field=models.ForeignKey(default=1, limit_choices_to=diffusion.models.main_event_false, on_delete=django.db.models.deletion.PROTECT, to='production.Event'),
        ),
        migrations.AddField(
            model_name='award',
            name='artist',
            field=models.ManyToManyField(blank=True, help_text='Staff or Artist', limit_choices_to=diffusion.models.staff_and_artist_user_limit, related_name='award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='artwork',
            field=models.ManyToManyField(blank=True, related_name='award', to='production.Artwork'),
        ),
        migrations.AddField(
            model_name='award',
            name='event',
            field=models.ForeignKey(limit_choices_to=diffusion.models.main_event_false, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='production.Event'),
        ),
        migrations.AddField(
            model_name='award',
            name='giver',
            field=models.ManyToManyField(blank=True, help_text='Who hands the arward', related_name='give_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='meta_award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='diffusion.MetaAward'),
        ),
        migrations.AddField(
            model_name='award',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='people.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='diffusion',
            unique_together={('id', 'artwork', 'event')},
        ),
    ]
