# Generated by Django 2.2.6 on 2019-12-20 09:07

import diffusion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='event',
            field=models.ForeignKey(limit_choices_to=diffusion.models.main_event_false, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='award',
            name='meta_award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='diffusion.MetaAward'),
        ),
        migrations.AlterField(
            model_name='award',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='people.Organization'),
        ),
        migrations.AlterField(
            model_name='diffusion',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='diffusion', to='production.Artwork'),
        ),
        migrations.AlterField(
            model_name='diffusion',
            name='event',
            field=models.ForeignKey(default=1, limit_choices_to=diffusion.models.main_event_false, on_delete=django.db.models.deletion.PROTECT, to='production.Event'),
        ),
        migrations.AlterField(
            model_name='metaaward',
            name='event',
            field=models.ForeignKey(help_text='Main Event', limit_choices_to=diffusion.models.main_event_true, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_award', to='production.Event'),
        ),
        migrations.AlterField(
            model_name='metaaward',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_award', to='production.StaffTask'),
        ),
        migrations.AlterField(
            model_name='metaevent',
            name='event',
            field=models.OneToOneField(limit_choices_to=diffusion.models.main_event_true, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='meta_event', serialize=False, to='production.Event'),
        ),
    ]
