# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0003_diffusion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diffusion_meta',
            new_name='Diffusion',
        ),
    ]
