# Generated by Django 2.2.6 on 2020-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0005_migration_to_django2'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffusion',
            name='note',
            field=models.TextField(blank=True, help_text='Free note / category'),
        ),
        migrations.AlterUniqueTogether(
            name='diffusion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='diffusion',
            constraint=models.UniqueConstraint(fields=('artwork', 'event'), name='diffusion_unique'),
        ),
    ]
