# Generated by Django 5.1.7 on 2025-09-02 13:41

import diffusion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0006_alter_place_country"),
        ("production", "0013_film_create_languagesVOSUB_update_moviespec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="artist",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staffs or Artists only",
                limit_choices_to=diffusion.models.staff_and_artist_user_limit,
                related_name="award",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="artwork",
            field=models.ManyToManyField(
                blank=True,
                help_text="Artwork(s) that received the award (may be empty for artistic awards)",
                related_name="award",
                to="production.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="event",
            field=models.ForeignKey(
                help_text="Event where the award has been given (not main event)",
                limit_choices_to=diffusion.models.main_event_false,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="award",
                to="production.event",
            ),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="artwork",
            field=models.ForeignKey(
                help_text="Artwork that has been shown",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diffusion",
                to="production.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="event",
            field=models.ForeignKey(
                help_text="Event where the artwork has been shown (not main event)",
                limit_choices_to=diffusion.models.main_event_false,
                on_delete=django.db.models.deletion.PROTECT,
                to="production.event",
            ),
        ),
        migrations.AlterField(
            model_name="metaaward",
            name="event",
            field=models.ForeignKey(
                help_text="Main Event only",
                limit_choices_to=diffusion.models.main_event_true,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meta_award",
                to="production.event",
            ),
        ),
    ]
