# Generated by Django 2.2.6 on 2020-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_medium_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='gallery',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='media', to='assets.Gallery'),
        ),
    ]
