# Generated by Django 2.2.6 on 2021-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_migration_to_django2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='INE',
            field=models.CharField(blank=True, help_text='Identifiant National Etudiant (only French student) - 10 numbers + 1 letter ou 9 numbers + 2 letters', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='position_in_interview_waitlist',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Administration - Set the position in interview waitlist', null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='position_in_waitlist',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Administration - Set the position in waitlist', null=True),
        ),
    ]
