# Generated by Django 4.1 on 2024-02-08 08:34

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0007_adminorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='alphabetical_order',
            field=models.CharField(blank=True, help_text='Never displayed, discern first/last user-name and nickname', max_length=3),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_photo',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.make_filepath),
        ),
        migrations.AddField(
            model_name='artist',
            name='collectives',
            field=models.ManyToManyField(blank=True, help_text='Member of collectives', related_name='members', to='people.artist'),
        ),
        migrations.AddField(
            model_name='fresnoyprofile',
            name='deathdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', True), models.Q(('nickname__exact', ''), _negated=True)), models.Q(models.Q(('user__isnull', True), _negated=True), models.Q(('nickname__exact', ''), _negated=True)), models.Q(models.Q(('user__isnull', True), _negated=True), ('nickname__exact', '')), _connector='OR'), name='Artist or collective should be named'),
        ),
    ]
