# Generated by Django 4.1 on 2024-02-27 14:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_artist_collectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresnoyprofile',
            name='deathdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fresnoyprofile',
            name='birthplace_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fresnoyprofile',
            name='homeland_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fresnoyprofile',
            name='residence_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
    ]
