# Generated by Django 4.1 on 2024-06-25 11:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_profile_deathdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresnoyprofile',
            name='deathplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fresnoyprofile',
            name='deathplace_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
    ]
