# Generated by Django 4.1 on 2024-06-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_deathplace'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='Artist or collective should be named',
        ),
    ]
