# Generated by Django 5.1.7 on 2025-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_deathplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="artist_photo_copyright",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
