# Generated by Django 5.1.12 on 2025-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_copyright_main_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="fresnoyprofile",
            name="preferred_first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Prénom d'usage"
            ),
        ),
        migrations.AddField(
            model_name="fresnoyprofile",
            name="preferred_last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nom d'usage"
            ),
        ),
    ]
