# Generated by Django 5.1.15 on 2026-03-23 11:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_preferred_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fresnoyprofile",
            name="residence_country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2, null=True
            ),
        ),
    ]
