# Generated by Django 3.2.15 on 2022-09-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_meta_staff_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorganizationtask',
            options={'ordering': ['pk']},
        ),
    ]
